version: "3.9"
services:
  db:
    image: postgres:15
    container_name: agnos-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: agnos
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    build: .
    container_name: agnos-app
    environment:
      DATABASE_DSN: host=db user=postgres password=postgres dbname=agnos port=5432 sslmode=disable TimeZone=Asia/Bangkok
    depends_on:
      - db
    ports:
      - "8080:8080"

volumes:
  pgdata:
